<?php
$zutabeak = array (
	"Giltza",
	"Euskalkia",
	"Aditza",
	"Modua",
	"Aldia",
	"Forma",
	"Nor",
	"Nori",
	"Nork",
	"Eztabada",
	"Toka",
	"Noka",
	"Xuka",
	"Zuka",
	"En",
	"Ena",
	"Enean",
	"Enik",
	"Ela",
	"Elarik",
	"Elako",
	"Elakotz",
	"Elakoan",
	"Ba",
	"BaToka",
	"BaNoka",
	"BaEn",
	"BaEna",
	"BaEnik",
	"BaEnean",
	"BaEla",
	"BaElarik",
	"BaElako",
	"BaElakotz",
	"BaElakoan",
	"Bait",
	"BaitToka",
	"BaitNoka"
	);
$baldintzak = $zutabeak;
array_push($baldintzak, 
	"Muga",
	"Mugazero",
	"Mugabi",
	"Bilaketa",
	"edit");
$lowerak = array (
	"Nor",
	"Nori",
	"Nork",
	"Eztabada",
	"Toka",
	"Noka",
	"Xuka",
	"Zuka",
	"En",
	"Ena",
	"Enean",
	"Enik",
	"Ela",
	"Elarik",
	"Elako",
	"Elakotz",
	"Elakoan",
	"Ba",
	"BaToka",
	"BaNoka",
	"BaEn",
	"BaEna",
	"BaEnik",
	"BaEnean",
	"BaEla",
	"BaElarik",
	"BaElako",
	"BaElakotz",
	"BaElakoan",
	"Bait",
	"BaitToka",
	"BaitNoka"
	);

$tratamendua = array (
	array ("En","Eztabada + -(E)N"),
	array ("Ena","Eztabada + -(E)NA"),
	array ("Enean","Eztabada + -(E)NEAN"),
	array ("Enik","Eztabada + -(E)NIK"),
	array ("Ela","Eztabada + -(E)LA"),
	array ("Elarik","Eztabada + -(E)LARIK"),
	array ("Elako","Eztabada + -(E)LAKO"),
	array ("Elakotz","Eztabada + -(E)LAKOTZ"),
	array ("Elakoan","Eztabada + -(E)LAKOAN"),
	array ("Ba","BA + Eztabada"),
	array ("BaToka","BA + Toka"),
	array ("BaNoka","BA + Noka"),
	array ("BaEn","BA + Eztabada + -(E)N"),
	array ("BaEna","BA + Eztabada + -(E)NA"),
	array ("BaEnik","BA + Eztabada + -(E)NIK"),
	array ("BaEnean","BA + Eztabada + -(E)NEAN"),
	array ("BaEla","BA + Eztabada + -(E)LA"),
	array ("BaElarik","BA + Eztabada + -(E)LARIK"),
	array ("BaElako","BA + Eztabada + -(E)LAKO"),
	array ("BaElakotz","BA + Eztabada + -(E)LAKOTZ"),
	array ("BaElakoan","BA + Eztabada + -(E)LAKOAN"),
	array ("Bait","BAIT + Eztabada"),
	array ("BaitToka","BAIT + Toka"),
	array ("BaitNoka","BAIT + Noka")
	)

?>
